# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-15 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20200715_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='updated',
        ),
        migrations.AddField(
            model_name='restaurantlocation',
            name='ff',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
