# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-15 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20200715_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='ff',
        ),
        migrations.AddField(
            model_name='restaurantlocation',
            name='dd',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
