# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-15 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20200715_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantlocation',
            old_name='dd',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='restaurantlocation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
