# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-15 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0019_remove_restaurantlocation_my_date_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='updated',
        ),
    ]
