# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-15 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0024_restaurantlocation_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='category',
        ),
    ]
