# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-16 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20200716_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
