# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-16 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_school_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
