# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-16 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20200716_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
