# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-23 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import schools.validators


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_school_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[schools.validators.validate_location]),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=120, validators=[schools.validators.validate_name]),
        ),
    ]
